In [6]:
import pandas as pd
import numpy as np
import os

In [7]:
import pandas as pd
import os

raw_path = "../backend/data/raw"

def audit_dataset(file_name):
    print(f"\n📁 Auditing: {file_name}")
    
    df = pd.read_excel(os.path.join(raw_path, file_name))
    
    print("Shape:", df.shape)
    print("\nColumn Names:")
    print(df.columns.tolist())
    
    print("\nMissing Values:")
    print(df.isnull().sum())
    
    print("\nDuplicate Rows:", df.duplicated().sum())
    
    print("\nData Types:")
    print(df.dtypes)
    
    return df

haryana_df = audit_dataset("HaryanaScheme.xlsx")

📁 Auditing: HaryanaScheme.xlsx
Shape: (117, 10)

Column Names:
['scheme_id', 'scheme_name', 'ministry', 'max_age', 'max_income_lakhs', 'category', 'gender', 'states', 'benefits', 'apply_link']

Missing Values:
scheme_id           1
scheme_name         1
ministry            1
max_age             1
max_income_lakhs    1
category            1
gender              1
states              2
benefits            2
apply_link          2
dtype: int64

Duplicate Rows: 0

Data Types:
scheme_id           object
scheme_name         object
ministry            object
max_age             object
max_income_lakhs    object
category            object
gender              object
states              object
benefits            object
apply_link          object
dtype: object

In [8]:
haryana_df = audit_dataset("HaryanaScheme.xlsx")

📁 Auditing: HaryanaScheme.xlsx
Shape: (117, 10)

Column Names:
['scheme_id', 'scheme_name', 'ministry', 'max_age', 'max_income_lakhs', 'category', 'gender', 'states', 'benefits', 'apply_link']

Missing Values:
scheme_id           1
scheme_name         1
ministry            1
max_age             1
max_income_lakhs    1
category            1
gender              1
states              2
benefits            2
apply_link          2
dtype: int64

Duplicate Rows: 0

Data Types:
scheme_id           object
scheme_name         object
ministry            object
max_age             object
max_income_lakhs    object
category            object
gender              object
states              object
benefits            object
apply_link          object
dtype: object

In [9]:
haryana_df.head()

,scheme_id,scheme_name,ministry,max_age,max_income_lakhs,category,gender,states,benefits,apply_link
0,1,PM Jan Dhan Yojana,Finance,100,500,All,All,All India,Zero balance+₹2L insurance,https://www.myscheme.gov.in/
1,2,PM Ujjwala 2.0,Petroleum,65,0.8,BPL,Female,All India,Free LPG connection,https://www.myscheme.gov.in/
2,3,PM Kisan Samman Nidhi,Agriculture,65,0,Farmer,All,All India,₹6000/year,https://www.myscheme.gov.in/
3,4,PM SVANidhi,MSME,65,5,Street vendor,All,All India,₹10K-50K loan,https://www.myscheme.gov.in/
4,5,Mudra Yojana,MSME,60,20,Micro business,All,All India,₹50K-20L loans,https://www.myscheme.gov.in/

In [10]:
haryana_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   scheme_id         116 non-null    object
 1   scheme_name       116 non-null    object
 2   ministry          116 non-null    object
 3   max_age           116 non-null    object
 4   max_income_lakhs  116 non-null    object
 5   category          116 non-null    object
 6   gender            116 non-null    object
 7   states            115 non-null    object
 8   benefits          115 non-null    object
 9   apply_link        115 non-null    object
dtypes: object(10)
memory usage: 9.3+ KB

In [11]:
haryana_df.describe()

,scheme_id,scheme_name,ministry,max_age,max_income_lakhs,category,gender,states,benefits,apply_link
count,116,116,116,116,116,116,116,115,115,115
unique,116,116,46,17,14,86,6,11,114,1
top,1,PM Jan Dhan Yojana,Agriculture,65,0,Farmer,All,All India,Drone subsidy,https://www.myscheme.gov.in/
freq,1,1,26,39,71,9,90,81,2,115

In [12]:
haryana_df = haryana_df.drop_duplicates()

In [13]:
haryana_df.duplicated().sum()

np.int64(0)

In [14]:
haryana_df['max_age'] = pd.to_numeric(haryana_df['max_age'], errors='coerce')

In [15]:
haryana_df['max_age'].dtype

dtype('float64')

In [16]:
haryana_df['max_income_lakhs'] = pd.to_numeric(haryana_df['max_income_lakhs'], errors='coerce')

In [17]:
haryana_df['gender'].unique()

array(['All', 'Female', 'Haryana', 'Women', 'gender', 'Male', nan],
      dtype=object)

In [18]:
haryana_df['gender'] = haryana_df['gender'].str.strip().str.lower()

In [19]:
haryana_df['gender'] = haryana_df['gender'].replace({'women' : 'female'})

In [20]:
haryana_df['gender'].unique()

array(['all', 'female', 'haryana', 'gender', 'male', nan], dtype=object)

In [21]:
valid_genders = ['male' , 'female' , 'all']
haryana_df.loc[~haryana_df['gender'].isin(valid_genders), 'gender'] = 'all'

In [22]:
haryana_df['gender'].unique()

array(['all', 'female', 'male'], dtype=object)

In [23]:
haryana_df['max_income_lakhs'].unique()

array([500. ,   0.8,   0. ,   5. ,  20. ,   4. ,   2.5,   3. ,   2. ,
         8. ,   1.5,  10. ,   1.8,   nan])

In [24]:
haryana_df[haryana_df['max_income_lakhs'] == 500]

,scheme_id,scheme_name,ministry,max_age,max_income_lakhs,category,gender,states,benefits,apply_link
0,1,PM Jan Dhan Yojana,Finance,100.0,500.0,All,all,All India,Zero balance+₹2L insurance,https://www.myscheme.gov.in/
66,66,Credit Guarantee Fund MSME,Finance,65.0,500.0,MSME,all,All India,Collateral free loan,https://www.myscheme.gov.in/

In [25]:
# Step 1: Create flag
haryana_df['no_income_limit'] = haryana_df['max_income_lakhs'] >= 500

# Step 2: Replace 500 with NaN
haryana_df.loc[haryana_df['max_income_lakhs'] >= 500, 'max_income_lakhs'] = np.nan

In [26]:
# Missing income thresholds were imputed with a high sentinel value (999 lakhs) to logically represent no income cap while preserving numeric consistency.
haryana_df['max_income_lakhs'].fillna(999, inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_17612\3583032535.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  haryana_df['max_income_lakhs'].fillna(999, inplace=True)

In [27]:
haryana_df['max_income_lakhs'].isnull().sum()

np.int64(0)

In [28]:
haryana_df[haryana_df['max_income_lakhs'].isnull()]

Empty DataFrame
Columns: [scheme_id, scheme_name, ministry, max_age, max_income_lakhs, category, gender, states, benefits, apply_link, no_income_limit]
Index: []

In [29]:
haryana_df[haryana_df['scheme_id'] == 'scheme_id']

,scheme_id,scheme_name,ministry,max_age,max_income_lakhs,category,gender,states,benefits,apply_link,no_income_limit
60,scheme_id,scheme_name,ministry,NaN,999.0,category,all,states,benefits,https://www.myscheme.gov.in/,False

In [30]:
haryana_df = haryana_df[haryana_df['scheme_id'] != 'scheme_id']

In [31]:
haryana_df.reset_index(drop=True, inplace=True)

In [32]:
haryana_df.head()

,scheme_id,scheme_name,ministry,max_age,max_income_lakhs,category,gender,states,benefits,apply_link,no_income_limit
0,1,PM Jan Dhan Yojana,Finance,100.0,999.0,All,all,All India,Zero balance+₹2L insurance,https://www.myscheme.gov.in/,True
1,2,PM Ujjwala 2.0,Petroleum,65.0,0.8,BPL,female,All India,Free LPG connection,https://www.myscheme.gov.in/,False
2,3,PM Kisan Samman Nidhi,Agriculture,65.0,0.0,Farmer,all,All India,₹6000/year,https://www.myscheme.gov.in/,False
3,4,PM SVANidhi,MSME,65.0,5.0,Street vendor,all,All India,₹10K-50K loan,https://www.myscheme.gov.in/,False
4,5,Mudra Yojana,MSME,60.0,20.0,Micro business,all,All India,₹50K-20L loans,https://www.myscheme.gov.in/,False

In [33]:
haryana_df[haryana_df['max_income_lakhs'].isnull()]

Empty DataFrame
Columns: [scheme_id, scheme_name, ministry, max_age, max_income_lakhs, category, gender, states, benefits, apply_link, no_income_limit]
Index: []

In [34]:
haryana_df['max_income_lakhs'].fillna(999, inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_17612\2773479292.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  haryana_df['max_income_lakhs'].fillna(999, inplace=True)

In [35]:
haryana_df['max_income_lakhs'].isnull().sum()

np.int64(0)

In [36]:
haryana_df[['scheme_name','max_income_lakhs','no_income_limit']].head()

             scheme_name  max_income_lakhs  no_income_limit
0     PM Jan Dhan Yojana             999.0             True
1         PM Ujjwala 2.0               0.8            False
2  PM Kisan Samman Nidhi               0.0            False
3            PM SVANidhi               5.0            False
4           Mudra Yojana              20.0            False

In [37]:
haryana_df['max_age'].describe()

count     98.000000
mean      54.367347
std       16.171368
min        6.000000
25%       46.000000
50%       60.000000
75%       65.000000
max      100.000000
Name: max_age, dtype: float64

In [38]:
haryana_df['max_age'].isnull().sum()

np.int64(18)

In [39]:
haryana_df['no_age_limit'] = haryana_df['max_age'].isnull()
haryana_df['max_age'].fillna(120, inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_17612\3186875074.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  haryana_df['max_age'].fillna(120, inplace=True)

In [40]:
haryana_df['max_age'].isnull().sum()

np.int64(0)

In [41]:
haryana_df.isnull().sum()

scheme_id           1
scheme_name         1
ministry            1
max_age             0
max_income_lakhs    0
category            1
gender              0
states              2
benefits            2
apply_link          2
no_income_limit     0
no_age_limit        0
dtype: int64

In [42]:
# standardize text
haryana_df['states'] = haryana_df['states'].astype(str).str.strip()

haryana_df['states'] = haryana_df['states'].replace({'nan': np.nan, '': np.nan})

# fill missing
haryana_df['states'] = haryana_df['states'].fillna('Haryana')

# normalize case
haryana_df['states'] = haryana_df['states'].str.lower()

In [43]:
haryana_df['states'].isnull().sum()
haryana_df['states'].value_counts().head(10)

states
all india         81
all haryana       11
rural india        7
haryana            6
coastal states     4
ne states          2
state-wise         2
telangana          1
j&k                1
ne/telangana       1
Name: count, dtype: int64

In [44]:
haryana_df['states'] = haryana_df['states'].replace({
    'all haryana': 'haryana'
})

In [45]:
haryana_df['states'].value_counts().head(10)

states
all india         81
haryana           17
rural india        7
coastal states     4
ne states          2
state-wise         2
telangana          1
j&k                1
ne/telangana       1
Name: count, dtype: int64

In [46]:
haryana_df['benefits'] = haryana_df['benefits'].fillna('Not specified')

In [47]:
haryana_df['apply_link'] = haryana_df['apply_link'].fillna('Not available')

In [48]:
haryana_df.isnull().sum()

scheme_id           1
scheme_name         1
ministry            1
max_age             0
max_income_lakhs    0
category            1
gender              0
states              0
benefits            0
apply_link          0
no_income_limit     0
no_age_limit        0
dtype: int64

In [49]:
haryana_df.to_csv("../data/cleaned/schemes_cleaned.csv", index=False)

OSError: Cannot save file into a non-existent directory: '..\data\cleaned'